base_url = "https://twistoy.com"
title = "核桃的炼金工坊"
compile_sass = true

# highlight_code = true
# highlight_theme = "agola-dark"

build_search_index = false

generate_feed = true
feed_filename = "rss.xml"

theme = "arknights"
taxonomies = [
  {name = "tags", rss = true},
  {name = "categories", rss = true},
]

[extra]
favicon = "https://avatars.githubusercontent.com/u/6359934"
toc = true

author = "Hawtian Wang"
home_subtitle = "Atelier TwIStOy"
footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

doctor = "TwIStOy"
doctor_url = "mailto:hawtian.wang@twistoy.cn"
menus = [
    { link = "/categories", name = "CATEGORIES" },
    { link = "/tags", name = "TAGS" },
    { link = "/rss.xml", name = "RSS" },
    { link = "/about", name = "ABOUT" },
]

icp_enabled = true

[extra.author]
name = "Hawtian Wang"
email = "twistoy.wang@gmail.com"

[extra.google_analytics]
enable = true
id = "UA-87286014-1"

[extra.icp]
id = "黑 ICP 备 2020005142 号"
police_id = "黑公网安备 23011002000439 号"


