base_url = "https://twistoy.com"
title = "大地的炼金工房"
compile_sass = true
highlight_code = true
highlight_theme = "monokai"
build_search_index = false
generate_feed = true

theme = "zola-theme-mikoto"
taxonomies = [
  {name = "categories", rss = true},
  {name = "tags", rss = true},
]

[extra]
favicon = "https://avatars.githubusercontent.com/u/6359934"
author = "Hawtian Wang"
mikoto_title = "大地的炼金工房"
mikoto_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/atom.xml", name = "Rss"},
    {url = "$BASE_URL/about", name = "About"},
]

