name: Deploy CN
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: config.toml
          find: twistoy.com
          replace: twistoy.cn
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@0.1.2
        with:
          include: config.toml
          find: icp_enabled = false
          replace: icp_enabled = true
      - name: Install Zola Environments
        run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.12.0/zola-v0.12.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /tmp
      - name: Deploy
        run: ./deploy_cn.sh
        env:
          PAGES_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PAGES_REPOSITORY: TwIStOy/twistoy.github.io
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./public
          scp_target: ~/data/html/blog2
      - name: Delete old posts
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: rm -rf ~/data/html/blog && mv ~/data/html/blog2 ~/data/html/blog
