name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Deploy to github pages
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: master
          BUILD_DIR: .
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY: TwIStOy/twistoy.github.io
      - name: Install Zola Environments
        run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.12.0/zola-v0.12.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /tmp
      - name: Deploy to Tecent CloudBase
        uses: TencentCloudBase/cloudbase-action@v2.0.1
        with:
          envId: ${{ secrets.CLOUDBASEENVID }}
          secretId: ${{ secrets.CLOUDBASESECRETID }} 
          secretKey: ${{ secrets.CLOUDBASESECRETKEY }}
