name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Zola Environments
        run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.12.0/zola-v0.12.0-x86_64-unknown-linux-gnu.tar.gz" | tar xzf - -C /tmp
      - name: Deploy
        run: ./deploy.sh
        env:
          PAGES_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PAGES_REPOSITORY: TwIStOy/twistoy.github.io
      - name: SSH Server Deploy
        uses: kostya-ten/ssh-server-deploy@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          scp_source: ./public
          scp_target: /var/www/html/blog
